### ISSUE TITLE
How the agent subscribe broker?

### ISSUE THREAD

**Issue by yerdos** [rafiulgits/IotHub#9]
First this is a awesome project ,I really love it
I had few confuse
If any device send message to broker, then how the agent get that message?
In agent project when "MqttClientService.StartAsync" start or what this function mean?

**Comment by rafiulgits** [comment]
Please have a look on README file, 

Agent app subscribe for all mesaages by using wildcard topic, whenever broker broadcast any message agent will be notified.


Agent connect with Broker through MQTT, that StartAsync function actually initiate that connection

**Comment by yerdos** [comment]
> Please have a look on README file, 
> 
> Agent app subscribe for all mesaages by using wildcard topic, whenever broker broadcast any message agent will be notified.
> 
> Agent connect with Broker through MQTT, that StartAsync function actually initiate that connection
Thanks for answer 
I had run it and find it out to how its work
thanks again ,this is a really awesome project!

**Comment by rafiulgits** [comment]
It'll be great if you documented the installation process and create a pull request.

**Comment by yerdos** [comment]
> 

Ok  , I will

**Comment by rafiulgits** [comment]
Hello there,
Please have a look on README file,
Agent app subscribe for all mesaages by using wildcard topic, whenever
broker broadcast any message agent will be notified.

Agent connect with Broker through MQTT, that StartAsync function actually
initiate that connection

Regards
Rafiul Islam
